### PR TITLE
Enable ppc64le

### PR DESCRIPTION
**Pull request by tonigi**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tonigi** [comment]
@conda-forge-admin, please rerender

**Comment by tonigi** [comment]
Fails, apparently due to platform lacking "statsmodels" required by "seaborn" (?)

**Comment by tonigi** [comment]
@conda-forge-admin, please rerender

**Comment by IAlibay** [comment]
@tonigi thanks for working on this, sorry I've not had a chance to look at this yet (it's conference season) - I'm unlikely to have a look until the weekend, please feel free to ping me or @orbeckst if nothing happens!

**Comment by tonigi** [comment]
Uhm... Not sure it's worth the effort, just a nice-to-have. Installation of mdanalysis via PIP seems to work on ppc64le, which is great.

The ppc64le conda package that I was attempting here can't be built because of the lack of statsmodels (I triggered a rebuild today just in case it appeared).

**Comment by richardjgowers** [comment]
Seaborn (and statsmodels) are optional iirc, so maybe we can make that
dependency optional in the yml here?

**Comment by IAlibay** [comment]
This should be fixed with #61 - sorry for having taken so long, hopefully it is still of use.

**Pull request closed without merging**
