### PR TITLE
build on windows

### PR DESCRIPTION
**Pull request by kain88-de**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

lets try to build on windows after a rerender

### CODE REVIEW

**Comment by kain88-de** [comment]
why did you add the skip for windows again @richardjgowers. I thought we wanted to build this on windows?

**Comment by richardjgowers** [comment]
@kain88-de it's just for Python 2, @tylerjereddy understands this more, but I don't think Py2&Win should work: https://github.com/MDAnalysis/mdanalysis/pull/2093

**Comment by kain88-de** [comment]
please also do a rerender of the feedstock then.

**Comment by richardjgowers** [comment]
@conda-forge-admin, please rerender

**Comment by tylerjereddy** [comment]
Yeah, I think for Python 2.7 & the matching older MSVC we'd need C89 standard compliance in all our C source code

**Comment by kain88-de** [comment]
I changed our compilers to use the C99 standard last year. Can we skip python 2.7 on windows?

**Comment by tylerjereddy** [comment]
Yeah, I think we'll just skip 2.7 on windows

**Comment by richardjgowers** [comment]
So I think this is finished, it's just whether we merge **this** or do a 0.19.1 which fences off the "bad" features in Windows (see: https://github.com/MDAnalysis/mdanalysis/pull/2126)

**Comment by kain88-de** [comment]
Having a release with *bad* features sounds *bad*.

**Comment by richardjgowers** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
