### PR TITLE
Add numpy upper bound for 2.4.1

### PR DESCRIPTION
**Pull request by IAlibay**
We're going to release 2.4.2 soon-ish, but I'd like to also fix this version instead of just yanking it again (since it's been in the wild for ~ week).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by IAlibay** [comment]
@conda-forge-admin, please rerender

**Review by orbeckst — CHANGES_REQUESTED** [review]
Errors such as
```
The reported errors are:
- Encountered problems while solving:
-   - package numpy-1.21.3-py310h57288b1_1 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
...
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("numpy==1.21.3=py310h57288b1_1"), MatchSpec("python_abi=3.10[build=*_cp310]")}
```
indicate that there's something in the specs that doesn't work yet — I don't understand why this specific version  1.21.3 is required if the range of possible numpy versions is 1.20..1.23.

**Comment by IAlibay** [comment]
> specific version 1.21.3 is required if the range of possible numpy versions is 1.20..1.23.

py310 and py311 require higher minimum versions of NumPy. I'll have a look in a bit, I'm not sure why the feedstock would break by just adding an upper pin, something might have changed in conda-forge internally.

**Comment by IAlibay** [comment]
Ah ok yeah I know what's up, the upper pin should be 1.24 not 1.23, I read the docs as `<=` instead of just `<`

**Comment by IAlibay** [comment]
For context, here is the docs for it: https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-at-the-recipe-level (the upper_pin example is at the bottom of the section)

**Comment by IAlibay** [comment]
_should_ be good now @orbeckst

**Review by orbeckst — APPROVED** [review]

**Pull request merged**
